# Generated by Django 3.0.8 on 2020-07-11 10:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(default='管理员', max_length=255),
        ),
    ]
