# Generated by Django 3.0.8 on 2020-07-12 01:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dashboard', '0002_auto_20200711_1856'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zhihu_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('job', models.CharField(max_length=255)),
                ('school', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=255)),
                ('industry', models.CharField(max_length=255)),
                ('major', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'zhihu_user',
            },
        ),
    ]
