# Generated by Django 2.2.7 on 2020-07-13 03:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dashboard', '0004_auto_20200712_1000'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZhihuQue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('follow', models.CharField(max_length=255)),
                ('pageview', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'zhihu_que',
            },
        ),
    ]
