# Generated by Django 2.2.7 on 2020-07-13 10:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dashboard', '0005_zhihuque'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZhihuTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('count', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'zhihu_tag',
            },
        ),
    ]
